// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by lib/core/l10n/tool/generate_locales.dart
//
// This file provides a clean API for accessing translations
// without needing to call .tr() explicitly.
//
// Usage: Locales.Auth.email instead of LocaleKeys.auth_email.tr()
//
// NOTE: LocaleKeys is intentionally NOT exported from l10n.dart.
// Always use Locales for type-safe translations!

// ignore_for_file: no_hardcoded_strings, constant_identifier_names, non_constant_identifier_names

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

import 'locale_keys.g.dart';

/// Provides clean access to all translations without .tr() calls.
///
/// This class is auto-generated from LocaleKeys.g.dart.
/// To regenerate, run: dart run lib/core/l10n/tool/l10n_generate.dart
///
/// Supported locales: en, it
/// Fallback locale: en
///
/// Usage:
/// ```dart
/// Text(Locales.Auth.email)  // Nested access!
/// Text(Locales.pageNotFound)  // Root level access
///
/// // Access locale constants
/// supportedLocales: Locales.supportedLocales
/// fallbackLocale: Locales.fallbackLocale
/// ```
abstract class Locales {
  /// Supported locales auto-detected from translation files
  static const List<Locale> supportedLocales = [Locale('en'), Locale('it')];

  /// Fallback locale (default)
  static const Locale fallbackLocale = Locale('en');

  // Nested translations
  /// Translations for app
  static const App = _App._();

  /// Translations for appLogs
  static const AppLogs = _AppLogs._();

  /// Translations for claude
  static const Claude = _Claude._();

  /// Translations for editor
  static const Editor = _Editor._();

  /// Translations for sessions
  static const Sessions = _Sessions._();

  /// Translations for shell
  static const Shell = _Shell._();

  /// Translations for slashCommands
  static const SlashCommands = _SlashCommands._();

  /// Translations for workspace
  static const Workspace = _Workspace._();

}

/// Nested class for app translations
class _App {
  const _App._();

  String get title => LocaleKeys.app_title.tr();
}

/// Nested class for appLogs translations
class _AppLogs {
  const _AppLogs._();

  String get back => LocaleKeys.appLogs_back.tr();
  String get deleteAll => LocaleKeys.appLogs_deleteAll.tr();
  String get deleteAllConfirmBody => LocaleKeys.appLogs_deleteAllConfirmBody.tr();
  String get deleteAllConfirmCancel => LocaleKeys.appLogs_deleteAllConfirmCancel.tr();
  String get deleteAllConfirmOk => LocaleKeys.appLogs_deleteAllConfirmOk.tr();
  String get deleteAllConfirmTitle => LocaleKeys.appLogs_deleteAllConfirmTitle.tr();
  String get empty => LocaleKeys.appLogs_empty.tr();
  String get title => LocaleKeys.appLogs_title.tr();
  /// Translations for detail
  final Detail = const _AppLogsDetail._();

  /// Translations for session
  final Session = const _AppLogsSession._();

}

/// Nested class for detail translations
class _AppLogsDetail {
  const _AppLogsDetail._();

  String get empty => LocaleKeys.appLogs_detail_empty.tr();
  String get exception => LocaleKeys.appLogs_detail_exception.tr();
  String get filterLevel => LocaleKeys.appLogs_detail_filterLevel.tr();
  String get search => LocaleKeys.appLogs_detail_search.tr();
  String get stackTrace => LocaleKeys.appLogs_detail_stackTrace.tr();
  /// Translations for level
  final Level = const _AppLogsDetailLevel._();

}

/// Nested class for level translations
class _AppLogsDetailLevel {
  const _AppLogsDetailLevel._();

  String get critical => LocaleKeys.appLogs_detail_level_critical.tr();
  String get debug => LocaleKeys.appLogs_detail_level_debug.tr();
  String get error => LocaleKeys.appLogs_detail_level_error.tr();
  String get info => LocaleKeys.appLogs_detail_level_info.tr();
  String get verbose => LocaleKeys.appLogs_detail_level_verbose.tr();
  String get warning => LocaleKeys.appLogs_detail_level_warning.tr();
}

/// Nested class for session translations
class _AppLogsSession {
  const _AppLogsSession._();

  String get delete => LocaleKeys.appLogs_session_delete.tr();
  String get deleteConfirmBody => LocaleKeys.appLogs_session_deleteConfirmBody.tr();
  String get deleteConfirmCancel => LocaleKeys.appLogs_session_deleteConfirmCancel.tr();
  String get deleteConfirmOk => LocaleKeys.appLogs_session_deleteConfirmOk.tr();
  String get deleteConfirmTitle => LocaleKeys.appLogs_session_deleteConfirmTitle.tr();
  String errors({required String count}) {
    return LocaleKeys.appLogs_session_errors.tr(namedArgs: {
      'count': count,
    });
  }

  String get inProgress => LocaleKeys.appLogs_session_inProgress.tr();
  String total({required String count}) {
    return LocaleKeys.appLogs_session_total.tr(namedArgs: {
      'count': count,
    });
  }

  String warnings({required String count}) {
    return LocaleKeys.appLogs_session_warnings.tr(namedArgs: {
      'count': count,
    });
  }

}

/// Nested class for claude translations
class _Claude {
  const _Claude._();

  /// Translations for askUser
  final AskUser = const _ClaudeAskUser._();

  /// Translations for effort
  final Effort = const _ClaudeEffort._();

  /// Translations for empty
  final Empty = const _ClaudeEmpty._();

  /// Translations for error
  final Error = const _ClaudeError._();

  /// Translations for message
  final Message = const _ClaudeMessage._();

  /// Translations for model
  final Model = const _ClaudeModel._();

  /// Translations for permission
  final Permission = const _ClaudePermission._();

  /// Translations for permissionRequest
  final PermissionRequest = const _ClaudePermissionRequest._();

  /// Translations for terminal
  final Terminal = const _ClaudeTerminal._();

  /// Translations for thinking
  final Thinking = const _ClaudeThinking._();

}

/// Nested class for askUser translations
class _ClaudeAskUser {
  const _ClaudeAskUser._();

  String get answeredLabel => LocaleKeys.claude_askUser_answeredLabel.tr();
  String get back => LocaleKeys.claude_askUser_back.tr();
  String get multiSelectHint => LocaleKeys.claude_askUser_multiSelectHint.tr();
  String get next => LocaleKeys.claude_askUser_next.tr();
  String get otherOption => LocaleKeys.claude_askUser_otherOption.tr();
  String get otherPlaceholder => LocaleKeys.claude_askUser_otherPlaceholder.tr();
  String stepCounter({required String current, required String total}) {
    return LocaleKeys.claude_askUser_stepCounter.tr(namedArgs: {
      'current': current,
      'total': total,
    });
  }

  String get submit => LocaleKeys.claude_askUser_submit.tr();
  String get title => LocaleKeys.claude_askUser_title.tr();
}

/// Nested class for effort translations
class _ClaudeEffort {
  const _ClaudeEffort._();

  String get high => LocaleKeys.claude_effort_high.tr();
  String get low => LocaleKeys.claude_effort_low.tr();
  String get max => LocaleKeys.claude_effort_max.tr();
  String get medium => LocaleKeys.claude_effort_medium.tr();
  String get xhigh => LocaleKeys.claude_effort_xhigh.tr();
}

/// Nested class for empty translations
class _ClaudeEmpty {
  const _ClaudeEmpty._();

  String get hint => LocaleKeys.claude_empty_hint.tr();
  String get title => LocaleKeys.claude_empty_title.tr();
}

/// Nested class for error translations
class _ClaudeError {
  const _ClaudeError._();

  String get binaryNotFound => LocaleKeys.claude_error_binaryNotFound.tr();
  String exitedNonZero({required String code}) {
    return LocaleKeys.claude_error_exitedNonZero.tr(namedArgs: {
      'code': code,
    });
  }

  String get killed => LocaleKeys.claude_error_killed.tr();
  String get parseFailed => LocaleKeys.claude_error_parseFailed.tr();
  String rateLimited({required String status}) {
    return LocaleKeys.claude_error_rateLimited.tr(namedArgs: {
      'status': status,
    });
  }

  String spawnFailed({required String message}) {
    return LocaleKeys.claude_error_spawnFailed.tr(namedArgs: {
      'message': message,
    });
  }

}

/// Nested class for message translations
class _ClaudeMessage {
  const _ClaudeMessage._();

  String get assistantLabel => LocaleKeys.claude_message_assistantLabel.tr();
  String get completionStub => LocaleKeys.claude_message_completionStub.tr();
  String get scrollToBottomTooltip => LocaleKeys.claude_message_scrollToBottomTooltip.tr();
  String get systemLabel => LocaleKeys.claude_message_systemLabel.tr();
  String get toolCompleted => LocaleKeys.claude_message_toolCompleted.tr();
  String get toolError => LocaleKeys.claude_message_toolError.tr();
  String get toolErrorOutput => LocaleKeys.claude_message_toolErrorOutput.tr();
  String toolGroupDone({required String n}) {
    return LocaleKeys.claude_message_toolGroupDone.tr(namedArgs: {
      'n': n,
    });
  }

  String toolGroupErrors({required String n}) {
    return LocaleKeys.claude_message_toolGroupErrors.tr(namedArgs: {
      'n': n,
    });
  }

  String toolGroupRunning({required String n}) {
    return LocaleKeys.claude_message_toolGroupRunning.tr(namedArgs: {
      'n': n,
    });
  }

  String toolGroupTitle({required String count}) {
    return LocaleKeys.claude_message_toolGroupTitle.tr(namedArgs: {
      'count': count,
    });
  }

  String get toolInput => LocaleKeys.claude_message_toolInput.tr();
  String get toolPrefix => LocaleKeys.claude_message_toolPrefix.tr();
  String get toolResult => LocaleKeys.claude_message_toolResult.tr();
  String get toolRunning => LocaleKeys.claude_message_toolRunning.tr();
}

/// Nested class for model translations
class _ClaudeModel {
  const _ClaudeModel._();

  String get haiku => LocaleKeys.claude_model_haiku.tr();
  String get opus => LocaleKeys.claude_model_opus.tr();
  String get sonnet => LocaleKeys.claude_model_sonnet.tr();
}

/// Nested class for permission translations
class _ClaudePermission {
  const _ClaudePermission._();

  String get acceptEdits => LocaleKeys.claude_permission_acceptEdits.tr();
  String get bypassPermissions => LocaleKeys.claude_permission_bypassPermissions.tr();
  String get default$ => LocaleKeys.claude_permission_default.tr();
  String get plan => LocaleKeys.claude_permission_plan.tr();
}

/// Nested class for permissionRequest translations
class _ClaudePermissionRequest {
  const _ClaudePermissionRequest._();

  String get allowAlways => LocaleKeys.claude_permissionRequest_allowAlways.tr();
  String get allowOnce => LocaleKeys.claude_permissionRequest_allowOnce.tr();
  String get answeredAllowAlways => LocaleKeys.claude_permissionRequest_answeredAllowAlways.tr();
  String get answeredAllowOnce => LocaleKeys.claude_permissionRequest_answeredAllowOnce.tr();
  String get answeredDeny => LocaleKeys.claude_permissionRequest_answeredDeny.tr();
  String get deny => LocaleKeys.claude_permissionRequest_deny.tr();
  String get inputLabel => LocaleKeys.claude_permissionRequest_inputLabel.tr();
  String subtitle({required String tool}) {
    return LocaleKeys.claude_permissionRequest_subtitle.tr(namedArgs: {
      'tool': tool,
    });
  }

  String get title => LocaleKeys.claude_permissionRequest_title.tr();
}

/// Nested class for terminal translations
class _ClaudeTerminal {
  const _ClaudeTerminal._();

  String get title => LocaleKeys.claude_terminal_title.tr();
  /// Translations for actions
  final Actions = const _ClaudeTerminalActions._();

  /// Translations for effort
  final Effort = const _ClaudeTerminalEffort._();

  /// Translations for input
  final Input = const _ClaudeTerminalInput._();

  /// Translations for mcp
  final Mcp = const _ClaudeTerminalMcp._();

  /// Translations for model
  final Model = const _ClaudeTerminalModel._();

  /// Translations for permission
  final Permission = const _ClaudeTerminalPermission._();

  /// Translations for status
  final Status = const _ClaudeTerminalStatus._();

  /// Translations for thinking
  final Thinking = const _ClaudeTerminalThinking._();

}

/// Nested class for actions translations
class _ClaudeTerminalActions {
  const _ClaudeTerminalActions._();

  String get clear => LocaleKeys.claude_terminal_actions_clear.tr();
  String get newSession => LocaleKeys.claude_terminal_actions_newSession.tr();
}

/// Nested class for effort translations
class _ClaudeTerminalEffort {
  const _ClaudeTerminalEffort._();

  String get label => LocaleKeys.claude_terminal_effort_label.tr();
  String get tooltip => LocaleKeys.claude_terminal_effort_tooltip.tr();
}

/// Nested class for input translations
class _ClaudeTerminalInput {
  const _ClaudeTerminalInput._();

  String get escConfirmStop => LocaleKeys.claude_terminal_input_escConfirmStop.tr();
  String get placeholder => LocaleKeys.claude_terminal_input_placeholder.tr();
  String get placeholderQueueing => LocaleKeys.claude_terminal_input_placeholderQueueing.tr();
  String get placeholderRunning => LocaleKeys.claude_terminal_input_placeholderRunning.tr();
  String get send => LocaleKeys.claude_terminal_input_send.tr();
  String get stop => LocaleKeys.claude_terminal_input_stop.tr();
  /// Translations for attachments
  final Attachments = const _ClaudeTerminalInputAttachments._();

  /// Translations for dictation
  final Dictation = const _ClaudeTerminalInputDictation._();

  /// Translations for queue
  final Queue = const _ClaudeTerminalInputQueue._();

}

/// Nested class for attachments translations
class _ClaudeTerminalInputAttachments {
  const _ClaudeTerminalInputAttachments._();

  String get addFile => LocaleKeys.claude_terminal_input_attachments_addFile.tr();
  String get addFolder => LocaleKeys.claude_terminal_input_attachments_addFolder.tr();
  String get addScreenshot => LocaleKeys.claude_terminal_input_attachments_addScreenshot.tr();
  String get dropHint => LocaleKeys.claude_terminal_input_attachments_dropHint.tr();
  String get removeTooltip => LocaleKeys.claude_terminal_input_attachments_removeTooltip.tr();
  String screenshotDisplay({required String index}) {
    return LocaleKeys.claude_terminal_input_attachments_screenshotDisplay.tr(namedArgs: {
      'index': index,
    });
  }

  String get screenshotError => LocaleKeys.claude_terminal_input_attachments_screenshotError.tr();
  String get screenshotFullScreen => LocaleKeys.claude_terminal_input_attachments_screenshotFullScreen.tr();
  String get screenshotPickDisplay => LocaleKeys.claude_terminal_input_attachments_screenshotPickDisplay.tr();
  String get screenshotPreview => LocaleKeys.claude_terminal_input_attachments_screenshotPreview.tr();
  String get screenshotPreviewAttach => LocaleKeys.claude_terminal_input_attachments_screenshotPreviewAttach.tr();
  String get screenshotPreviewClose => LocaleKeys.claude_terminal_input_attachments_screenshotPreviewClose.tr();
  String get screenshotPreviewDiscard => LocaleKeys.claude_terminal_input_attachments_screenshotPreviewDiscard.tr();
  String get screenshotPreviewTitle => LocaleKeys.claude_terminal_input_attachments_screenshotPreviewTitle.tr();
  String get screenshotRegion => LocaleKeys.claude_terminal_input_attachments_screenshotRegion.tr();
  String get screenshotWindow => LocaleKeys.claude_terminal_input_attachments_screenshotWindow.tr();
}

/// Nested class for dictation translations
class _ClaudeTerminalInputDictation {
  const _ClaudeTerminalInputDictation._();

  String backendError({required String message}) {
    return LocaleKeys.claude_terminal_input_dictation_backendError.tr(namedArgs: {
      'message': message,
    });
  }

  String get modeMenuHold => LocaleKeys.claude_terminal_input_dictation_modeMenuHold.tr();
  String get modeMenuTap => LocaleKeys.claude_terminal_input_dictation_modeMenuTap.tr();
  String get noSpeechDetected => LocaleKeys.claude_terminal_input_dictation_noSpeechDetected.tr();
  String get permissionDenied => LocaleKeys.claude_terminal_input_dictation_permissionDenied.tr();
  String get tooltipIdleHold => LocaleKeys.claude_terminal_input_dictation_tooltipIdleHold.tr();
  String get tooltipIdleTap => LocaleKeys.claude_terminal_input_dictation_tooltipIdleTap.tr();
  String get tooltipListening => LocaleKeys.claude_terminal_input_dictation_tooltipListening.tr();
  String get tooltipListeningTap => LocaleKeys.claude_terminal_input_dictation_tooltipListeningTap.tr();
  String get tooltipUnavailable => LocaleKeys.claude_terminal_input_dictation_tooltipUnavailable.tr();
  String unsupportedLanguage({required String language}) {
    return LocaleKeys.claude_terminal_input_dictation_unsupportedLanguage.tr(namedArgs: {
      'language': language,
    });
  }

}

/// Nested class for queue translations
class _ClaudeTerminalInputQueue {
  const _ClaudeTerminalInputQueue._();

  String get editPlaceholder => LocaleKeys.claude_terminal_input_queue_editPlaceholder.tr();
  String get label => LocaleKeys.claude_terminal_input_queue_label.tr();
  String get removeTooltip => LocaleKeys.claude_terminal_input_queue_removeTooltip.tr();
  String get send => LocaleKeys.claude_terminal_input_queue_send.tr();
}

/// Nested class for mcp translations
class _ClaudeTerminalMcp {
  const _ClaudeTerminalMcp._();

  String get authenticate => LocaleKeys.claude_terminal_mcp_authenticate.tr();
  String get disabledLabel => LocaleKeys.claude_terminal_mcp_disabledLabel.tr();
  String get empty => LocaleKeys.claude_terminal_mcp_empty.tr();
  String get error => LocaleKeys.claude_terminal_mcp_error.tr();
  String get label => LocaleKeys.claude_terminal_mcp_label.tr();
  String get loading => LocaleKeys.claude_terminal_mcp_loading.tr();
  String get refresh => LocaleKeys.claude_terminal_mcp_refresh.tr();
  String get title => LocaleKeys.claude_terminal_mcp_title.tr();
  String get toggleError => LocaleKeys.claude_terminal_mcp_toggleError.tr();
  String get toggleNoSession => LocaleKeys.claude_terminal_mcp_toggleNoSession.tr();
  String get tooltip => LocaleKeys.claude_terminal_mcp_tooltip.tr();
  /// Translations for status
  final Status = const _ClaudeTerminalMcpStatus._();

}

/// Nested class for status translations
class _ClaudeTerminalMcpStatus {
  const _ClaudeTerminalMcpStatus._();

  String get connected => LocaleKeys.claude_terminal_mcp_status_connected.tr();
  String get failed => LocaleKeys.claude_terminal_mcp_status_failed.tr();
  String get needsAuth => LocaleKeys.claude_terminal_mcp_status_needsAuth.tr();
  String get unknown => LocaleKeys.claude_terminal_mcp_status_unknown.tr();
}

/// Nested class for model translations
class _ClaudeTerminalModel {
  const _ClaudeTerminalModel._();

  String get label => LocaleKeys.claude_terminal_model_label.tr();
  String get tooltip => LocaleKeys.claude_terminal_model_tooltip.tr();
}

/// Nested class for permission translations
class _ClaudeTerminalPermission {
  const _ClaudeTerminalPermission._();

  String get label => LocaleKeys.claude_terminal_permission_label.tr();
  String get tooltip => LocaleKeys.claude_terminal_permission_tooltip.tr();
  /// Translations for warning
  final Warning = const _ClaudeTerminalPermissionWarning._();

}

/// Nested class for warning translations
class _ClaudeTerminalPermissionWarning {
  const _ClaudeTerminalPermissionWarning._();

  String get default$ => LocaleKeys.claude_terminal_permission_warning_default.tr();
}

/// Nested class for status translations
class _ClaudeTerminalStatus {
  const _ClaudeTerminalStatus._();

  String get connecting => LocaleKeys.claude_terminal_status_connecting.tr();
  String get error => LocaleKeys.claude_terminal_status_error.tr();
  String get idle => LocaleKeys.claude_terminal_status_idle.tr();
  String get noWorkspace => LocaleKeys.claude_terminal_status_noWorkspace.tr();
  String get running => LocaleKeys.claude_terminal_status_running.tr();
  String get sessionDead => LocaleKeys.claude_terminal_status_sessionDead.tr();
}

/// Nested class for thinking translations
class _ClaudeTerminalThinking {
  const _ClaudeTerminalThinking._();

  String get label => LocaleKeys.claude_terminal_thinking_label.tr();
  String get tooltip => LocaleKeys.claude_terminal_thinking_tooltip.tr();
}

/// Nested class for thinking translations
class _ClaudeThinking {
  const _ClaudeThinking._();

  String get off => LocaleKeys.claude_thinking_off.tr();
  String get think => LocaleKeys.claude_thinking_think.tr();
  String get thinkHard => LocaleKeys.claude_thinking_thinkHard.tr();
  String get ultrathink => LocaleKeys.claude_thinking_ultrathink.tr();
}

/// Nested class for editor translations
class _Editor {
  const _Editor._();

  String get binaryFile => LocaleKeys.editor_binaryFile.tr();
  String get fileLoadError => LocaleKeys.editor_fileLoadError.tr();
  String get fileTooLarge => LocaleKeys.editor_fileTooLarge.tr();
  String get noFileOpen => LocaleKeys.editor_noFileOpen.tr();
  /// Translations for find
  final Find = const _EditorFind._();

  /// Translations for image
  final Image = const _EditorImage._();

  /// Translations for markdown
  final Markdown = const _EditorMarkdown._();

  /// Translations for openFiles
  final OpenFiles = const _EditorOpenFiles._();

  /// Translations for pdf
  final Pdf = const _EditorPdf._();

  /// Translations for tab
  final Tab = const _EditorTab._();

  /// Translations for unsupported
  final Unsupported = const _EditorUnsupported._();

}

/// Nested class for find translations
class _EditorFind {
  const _EditorFind._();

  String get caseSensitive => LocaleKeys.editor_find_caseSensitive.tr();
  String get close => LocaleKeys.editor_find_close.tr();
  String get hint => LocaleKeys.editor_find_hint.tr();
  String get next => LocaleKeys.editor_find_next.tr();
  String get noResults => LocaleKeys.editor_find_noResults.tr();
  String get previous => LocaleKeys.editor_find_previous.tr();
  String get regex => LocaleKeys.editor_find_regex.tr();
}

/// Nested class for image translations
class _EditorImage {
  const _EditorImage._();

  String get loadError => LocaleKeys.editor_image_loadError.tr();
}

/// Nested class for markdown translations
class _EditorMarkdown {
  const _EditorMarkdown._();

  String get toggleRendered => LocaleKeys.editor_markdown_toggleRendered.tr();
  String get toggleSource => LocaleKeys.editor_markdown_toggleSource.tr();
}

/// Nested class for openFiles translations
class _EditorOpenFiles {
  const _EditorOpenFiles._();

  String get closeAll => LocaleKeys.editor_openFiles_closeAll.tr();
  String get empty => LocaleKeys.editor_openFiles_empty.tr();
  String get noMatches => LocaleKeys.editor_openFiles_noMatches.tr();
  String get searchHint => LocaleKeys.editor_openFiles_searchHint.tr();
  String get tooltip => LocaleKeys.editor_openFiles_tooltip.tr();
}

/// Nested class for pdf translations
class _EditorPdf {
  const _EditorPdf._();

  String get loadError => LocaleKeys.editor_pdf_loadError.tr();
}

/// Nested class for tab translations
class _EditorTab {
  const _EditorTab._();

  String get close => LocaleKeys.editor_tab_close.tr();
  String get closeAll => LocaleKeys.editor_tab_closeAll.tr();
}

/// Nested class for unsupported translations
class _EditorUnsupported {
  const _EditorUnsupported._();

  String get revealInFinder => LocaleKeys.editor_unsupported_revealInFinder.tr();
  String get title => LocaleKeys.editor_unsupported_title.tr();
}

/// Nested class for sessions translations
class _Sessions {
  const _Sessions._();

  /// Translations for list
  final List = const _SessionsList._();

  /// Translations for preview
  final Preview = const _SessionsPreview._();

}

/// Nested class for list translations
class _SessionsList {
  const _SessionsList._();

  String get empty => LocaleKeys.sessions_list_empty.tr();
  String get headerLabel => LocaleKeys.sessions_list_headerLabel.tr();
  String get newChat => LocaleKeys.sessions_list_newChat.tr();
  String get refresh => LocaleKeys.sessions_list_refresh.tr();
  String get search => LocaleKeys.sessions_list_search.tr();
  String get untitled => LocaleKeys.sessions_list_untitled.tr();
  /// Translations for relativeDate
  final RelativeDate = const _SessionsListRelativeDate._();

}

/// Nested class for relativeDate translations
class _SessionsListRelativeDate {
  const _SessionsListRelativeDate._();

  String hoursAgo({required String n}) {
    return LocaleKeys.sessions_list_relativeDate_hoursAgo.tr(namedArgs: {
      'n': n,
    });
  }

  String minutesAgo({required String n}) {
    return LocaleKeys.sessions_list_relativeDate_minutesAgo.tr(namedArgs: {
      'n': n,
    });
  }

  String get now => LocaleKeys.sessions_list_relativeDate_now.tr();
  String get yesterday => LocaleKeys.sessions_list_relativeDate_yesterday.tr();
}

/// Nested class for preview translations
class _SessionsPreview {
  const _SessionsPreview._();

  String get delete => LocaleKeys.sessions_preview_delete.tr();
  String get deleteConfirmBody => LocaleKeys.sessions_preview_deleteConfirmBody.tr();
  String get deleteConfirmCancel => LocaleKeys.sessions_preview_deleteConfirmCancel.tr();
  String get deleteConfirmOk => LocaleKeys.sessions_preview_deleteConfirmOk.tr();
  String get deleteConfirmTitle => LocaleKeys.sessions_preview_deleteConfirmTitle.tr();
  String get empty => LocaleKeys.sessions_preview_empty.tr();
  String get export => LocaleKeys.sessions_preview_export.tr();
  String exportDone({required String path}) {
    return LocaleKeys.sessions_preview_exportDone.tr(namedArgs: {
      'path': path,
    });
  }

  String get resume => LocaleKeys.sessions_preview_resume.tr();
  String get resumeConfirmBody => LocaleKeys.sessions_preview_resumeConfirmBody.tr();
  String get resumeConfirmCancel => LocaleKeys.sessions_preview_resumeConfirmCancel.tr();
  String get resumeConfirmOk => LocaleKeys.sessions_preview_resumeConfirmOk.tr();
  String get resumeConfirmTitle => LocaleKeys.sessions_preview_resumeConfirmTitle.tr();
}

/// Nested class for shell translations
class _Shell {
  const _Shell._();

  /// Translations for activity
  final Activity = const _ShellActivity._();

  /// Translations for shortcuts
  final Shortcuts = const _ShellShortcuts._();

  /// Translations for sidePanel
  final SidePanel = const _ShellSidePanel._();

  /// Translations for workspace
  final Workspace = const _ShellWorkspace._();

}

/// Nested class for activity translations
class _ShellActivity {
  const _ShellActivity._();

  String get comingLaterSuffix => LocaleKeys.shell_activity_comingLaterSuffix.tr();
  String get explorer => LocaleKeys.shell_activity_explorer.tr();
  String get git => LocaleKeys.shell_activity_git.tr();
  String get logs => LocaleKeys.shell_activity_logs.tr();
  String get search => LocaleKeys.shell_activity_search.tr();
  String get sessions => LocaleKeys.shell_activity_sessions.tr();
  String get settings => LocaleKeys.shell_activity_settings.tr();
}

/// Nested class for shortcuts translations
class _ShellShortcuts {
  const _ShellShortcuts._();

  String get alreadyAttached => LocaleKeys.shell_shortcuts_alreadyAttached.tr();
  String attachedFile({required String name}) {
    return LocaleKeys.shell_shortcuts_attachedFile.tr(namedArgs: {
      'name': name,
    });
  }

  String attachedRange({required String name}) {
    return LocaleKeys.shell_shortcuts_attachedRange.tr(namedArgs: {
      'name': name,
    });
  }

  String effortChanged({required String value}) {
    return LocaleKeys.shell_shortcuts_effortChanged.tr(namedArgs: {
      'value': value,
    });
  }

  String get noActiveWorkspace => LocaleKeys.shell_shortcuts_noActiveWorkspace.tr();
  String permissionChanged({required String value}) {
    return LocaleKeys.shell_shortcuts_permissionChanged.tr(namedArgs: {
      'value': value,
    });
  }

  String thinkingChanged({required String value}) {
    return LocaleKeys.shell_shortcuts_thinkingChanged.tr(namedArgs: {
      'value': value,
    });
  }

}

/// Nested class for sidePanel translations
class _ShellSidePanel {
  const _ShellSidePanel._();

  String get emptyFolder => LocaleKeys.shell_sidePanel_emptyFolder.tr();
  String get explorerLabel => LocaleKeys.shell_sidePanel_explorerLabel.tr();
  String get loadError => LocaleKeys.shell_sidePanel_loadError.tr();
  String get refresh => LocaleKeys.shell_sidePanel_refresh.tr();
  String get toggleHiddenHide => LocaleKeys.shell_sidePanel_toggleHiddenHide.tr();
  String get toggleHiddenShow => LocaleKeys.shell_sidePanel_toggleHiddenShow.tr();
}

/// Nested class for workspace translations
class _ShellWorkspace {
  const _ShellWorkspace._();

  String get toggleToFullscreen => LocaleKeys.shell_workspace_toggleToFullscreen.tr();
  String get toggleToWorkspace => LocaleKeys.shell_workspace_toggleToWorkspace.tr();
}

/// Nested class for slashCommands translations
class _SlashCommands {
  const _SlashCommands._();

  String get empty => LocaleKeys.slashCommands_empty.tr();
  /// Translations for chip
  final Chip = const _SlashCommandsChip._();

  /// Translations for source
  final Source = const _SlashCommandsSource._();

}

/// Nested class for chip translations
class _SlashCommandsChip {
  const _SlashCommandsChip._();

  String get removeTooltip => LocaleKeys.slashCommands_chip_removeTooltip.tr();
}

/// Nested class for source translations
class _SlashCommandsSource {
  const _SlashCommandsSource._();

  String get cliBuiltin => LocaleKeys.slashCommands_source_cliBuiltin.tr();
  String get plugin => LocaleKeys.slashCommands_source_plugin.tr();
  String get project => LocaleKeys.slashCommands_source_project.tr();
  String get skill => LocaleKeys.slashCommands_source_skill.tr();
  String get user => LocaleKeys.slashCommands_source_user.tr();
}

/// Nested class for workspace translations
class _Workspace {
  const _Workspace._();

  /// Translations for dropdown
  final Dropdown = const _WorkspaceDropdown._();

  /// Translations for emptyState
  final EmptyState = const _WorkspaceEmptyState._();

  /// Translations for picker
  final Picker = const _WorkspacePicker._();

}

/// Nested class for dropdown translations
class _WorkspaceDropdown {
  const _WorkspaceDropdown._();

  String get closeWorkspace => LocaleKeys.workspace_dropdown_closeWorkspace.tr();
  String get empty => LocaleKeys.workspace_dropdown_empty.tr();
  String get openFolder => LocaleKeys.workspace_dropdown_openFolder.tr();
}

/// Nested class for emptyState translations
class _WorkspaceEmptyState {
  const _WorkspaceEmptyState._();

  String get hint => LocaleKeys.workspace_emptyState_hint.tr();
  String get openFolder => LocaleKeys.workspace_emptyState_openFolder.tr();
}

/// Nested class for picker translations
class _WorkspacePicker {
  const _WorkspacePicker._();

  String get title => LocaleKeys.workspace_picker_title.tr();
}

